#!/usr/bin/env bash

# Convert training data from Avro to StreamSpot
cd /sbustreamspot-cdm
python translate_cdm_to_streamspot.py \
  --url $KAFKA_URL_IN --kafka-topic $KAFKA_TOPIC_IN --kafka-group $KAFKA_GROUP \
  --format avro --source kafka --concise --train > $TRAINING_DIR/train.ss
if [ $? -ne 0 ]; then
  echo "[sbustreamspot-cdm] FAIL!"
  exit 1
else
  echo "[sbustreamspot-cdm] SUCCESS"
fi
